[workspace]
resolver = "2"
members = [
  "rs_lib",
]

[workspace.dependencies]
sys_traits = "0.1.0-alpha.5"

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"

[patch.crates-io]
deno_path_util = { path = "../deno_path_util" }
sys_traits = { path = "../sys_traits" }