name: ci

on: [push, pull_request]

jobs:
  deno:
    name: deno_cache_dir ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'denoland:')
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v6
      - name: Install rust
        uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      - name: Format
        if: contains(matrix.os, 'ubuntu')
        run: cargo fmt --check && deno fmt --check
      - name: Clippy
        if: contains(matrix.os, 'ubuntu')
        run: cargo clippy --target=wasm32-unknown-unknown && deno lint
      - name: Build
        run: deno task build
      - name: Test
        run: deno task test

      - name: Publish JSR
        if: contains(matrix.os, 'ubuntu')
        run: deno run -A jsr:@david/publish-on-tag@0.1.3
